USE [master]
GO

/****** Object:  Database [Gorev_9_PersonelKayitDB]    Script Date: 1.09.2019 11:47:14 ******/
CREATE DATABASE [Gorev_9_PersonelKayitDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gorev_9_PersonelKayitDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Gorev_9_PersonelKayitDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gorev_9_PersonelKayitDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Gorev_9_PersonelKayitDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gorev_9_PersonelKayitDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET RECOVERY FULL 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET  MULTI_USER 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Gorev_9_PersonelKayitDB] SET  READ_WRITE 
GO

