//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eksin_EczaneOtomasyonProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilaclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilaclar()
        {
            this.SatisDetaylari = new HashSet<SatisDetaylari>();
        }
    
        public int IlacID { get; set; }
        public string IlacAdi { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public string KullanımBilgisi { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> StokDurumu { get; set; }
        public Nullable<int> KritikStokSeviyesi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Tedarikciler Tedarikciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisDetaylari> SatisDetaylari { get; set; }
    }
}
