//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eksin_EczaneOtomasyonProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisDetaylari
    {
        public int IlacID { get; set; }
        public int SatisID { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> UrunAdedi { get; set; }
    
        public virtual Ilaclar Ilaclar { get; set; }
        public virtual Satislar Satislar { get; set; }
    }
}
