//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eksin_EczaneOtomasyonProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satislar()
        {
            this.SatisDetaylari = new HashSet<SatisDetaylari>();
        }
    
        public int SatisID { get; set; }
        public Nullable<int> CalisanID { get; set; }
        public Nullable<int> MusteriTC { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
    
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisDetaylari> SatisDetaylari { get; set; }
    }
}
