//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eksin_EczaneOtomasyonProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tedarikciler()
        {
            this.Ilaclar = new HashSet<Ilaclar>();
        }
    
        public int TedarikciID { get; set; }
        public string TedarikciAdi { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string E_Posta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilaclar> Ilaclar { get; set; }
    }
}
