//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersSinavlari
    {
        public int DersSinavlariID { get; set; }
        public int DersID { get; set; }
        public int SinavDonemID { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual OgrenciSinavlari OgrenciSinavlari { get; set; }
        public virtual SinavDonemleri SinavDonemleri { get; set; }
    }
}
