//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int DuyuruID { get; set; }
        public string DuyuruMetin { get; set; }
        public System.DateTime DuyuruTarihi { get; set; }
        public string DosyaEki { get; set; }
        public int SorumluPersonel { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
