//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lise_Yönetim_DBEntities : DbContext
    {
        public Lise_Yönetim_DBEntities()
            : base("name=Lise_Yönetim_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<DersProgramları> DersProgramları { get; set; }
        public virtual DbSet<DersSinavlari> DersSinavlari { get; set; }
        public virtual DbSet<Duyurular> Duyurular { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<OgrenciBilgileri> OgrenciBilgileri { get; set; }
        public virtual DbSet<OgrenciDersleri> OgrenciDersleri { get; set; }
        public virtual DbSet<OgrenciDevamsizlik> OgrenciDevamsizlik { get; set; }
        public virtual DbSet<OgrenciDisiplinKayitlari> OgrenciDisiplinKayitlari { get; set; }
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<OgrenciSinavlari> OgrenciSinavlari { get; set; }
        public virtual DbSet<OgretmenBilgileri> OgretmenBilgileri { get; set; }
        public virtual DbSet<OgretmenBranslari> OgretmenBranslari { get; set; }
        public virtual DbSet<OgretmenDersleri> OgretmenDersleri { get; set; }
        public virtual DbSet<OgretmenDevamsizlik> OgretmenDevamsizlik { get; set; }
        public virtual DbSet<OgretmenDisiplinKayitlari> OgretmenDisiplinKayitlari { get; set; }
        public virtual DbSet<Ogretmenler> Ogretmenler { get; set; }
        public virtual DbSet<PersonelBilgileri> PersonelBilgileri { get; set; }
        public virtual DbSet<PersonelDevamsizlik> PersonelDevamsizlik { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<PersonelMeslekleri> PersonelMeslekleri { get; set; }
        public virtual DbSet<SinavDonemleri> SinavDonemleri { get; set; }
        public virtual DbSet<Siniflar> Siniflar { get; set; }
        public virtual DbSet<SinifOgrencileri> SinifOgrencileri { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
