//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretmenBilgileri
    {
        public int OgretmenID { get; set; }
        public string OgretmenTelefonu { get; set; }
        public string OgretmenMailAdresi { get; set; }
        public string OgretmenEvAdresi { get; set; }
        public Nullable<System.DateTime> OgretmenDogumTarihi { get; set; }
        public Nullable<bool> OgretmenMedeniDurum { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
