//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciSinavlari
    {
        public int OgrenciSinavlariID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> SinavNotu { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual DersSinavlari DersSinavlari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
