//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciBilgileri
    {
        public int OgrenciID { get; set; }
        public string OgrenciTelefonu { get; set; }
        public string OgrenciMailAdresi { get; set; }
        public string OgrenciEvAdresi { get; set; }
        public string VeliAdiSoyadi { get; set; }
        public string VeliTelefonu { get; set; }
        public string Veli2AdiSoyadi { get; set; }
        public string VeliTelefonu2 { get; set; }
        public Nullable<System.DateTime> OgrenciDogumTarihi { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
