//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDisiplinKayitlari
    {
        public int DisiplinID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public string DisiplinSebebi { get; set; }
        public Nullable<int> SorumluOgretmen { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
