//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.OgrenciDersleri = new HashSet<OgrenciDersleri>();
            this.OgrenciDevamsizlik = new HashSet<OgrenciDevamsizlik>();
            this.OgrenciDisiplinKayitlari = new HashSet<OgrenciDisiplinKayitlari>();
            this.OgrenciSinavlari = new HashSet<OgrenciSinavlari>();
            this.SinifOgrencileri = new HashSet<SinifOgrencileri>();
        }
    
        public int OgrenciID { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string OgrenciKimlikNo { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenciBilgileri OgrenciBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDersleri> OgrenciDersleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDevamsizlik> OgrenciDevamsizlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDisiplinKayitlari> OgrenciDisiplinKayitlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciSinavlari> OgrenciSinavlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinifOgrencileri> SinifOgrencileri { get; set; }
    }
}
