//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretmenDevamsizlik
    {
        public int OgretmenDevamsizlikID { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public Nullable<System.DateTime> DevamsizlikTarihi { get; set; }
        public string Mazereti { get; set; }
        public Nullable<bool> RaporBilgisi { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
