//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmenler()
        {
            this.OgrenciDisiplinKayitlari = new HashSet<OgrenciDisiplinKayitlari>();
            this.OgretmenDersleri = new HashSet<OgretmenDersleri>();
            this.OgretmenDevamsizlik = new HashSet<OgretmenDevamsizlik>();
            this.OgretmenDisiplinKayitlari = new HashSet<OgretmenDisiplinKayitlari>();
        }
    
        public int OgretmenID { get; set; }
        public string OgretmenAdi { get; set; }
        public string OgretmenSoyadi { get; set; }
        public string OgretmenKimlikNo { get; set; }
        public Nullable<int> OgretmenBrans { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDisiplinKayitlari> OgrenciDisiplinKayitlari { get; set; }
        public virtual OgretmenBilgileri OgretmenBilgileri { get; set; }
        public virtual OgretmenBranslari OgretmenBranslari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenDersleri> OgretmenDersleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenDevamsizlik> OgretmenDevamsizlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenDisiplinKayitlari> OgretmenDisiplinKayitlari { get; set; }
    }
}
