//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiseYonetim.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelBilgileri
    {
        public int PersonelID { get; set; }
        public string PersonelTelefonu { get; set; }
        public string PersonelMailAdresi { get; set; }
        public string PersonelEvAdresi { get; set; }
        public Nullable<System.DateTime> PersonelDogumTarihi { get; set; }
        public Nullable<bool> PersonelMedeniDurumu { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
